name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet Main-Tools/Main-Tools.sln restore
    - name: Build
      run: dotnet Main-Tools/Main-Tools.sln build --no-restore
    - name: Test
      run: dotnet Main-Tools/Main-Tools.sln test --no-build --verbosity normal
