// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using HospitalAPI;
//
//    var hospital = Hospital.FromJson(jsonString);

namespace HospitalAPI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Hospital
    {
        [JsonProperty("OntarioHospitalized")]
        public string OntarioHospitalized { get; set; }

        [JsonProperty("OntarioICU")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long OntarioIcu { get; set; }

        [JsonProperty("ICUPositiveCases")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IcuPositiveCases { get; set; }

        [JsonProperty("ICUNegativeCases")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IcuNegativeCases { get; set; }

        [JsonProperty("ICUOnVentilator")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IcuOnVentilator { get; set; }

        [JsonProperty("ICUOnVentilatorPositiveCases")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IcuOnVentilatorPositiveCases { get; set; }

        [JsonProperty("ICUOnVentilatorNegativeCases")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long IcuOnVentilatorNegativeCases { get; set; }
    }

    public partial class Hospital
    {
        public static Hospital FromJson(string json) => JsonConvert.DeserializeObject<Hospital>(json, HospitalAPI.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Hospital self) => JsonConvert.SerializeObject(self, HospitalAPI.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}
