// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TriviaAPI;
//
//    var trivia = Trivia.FromJson(jsonString);

namespace TriviaAPI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Microsoft.Azure.Mobile.Server;

    public partial class Trivia : EntityData
    {
        [JsonProperty("text")]
        public string Text { get; set; }

        [JsonProperty("number")]
        public long Number { get; set; }

        [JsonProperty("found")]
        public bool Found { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Trivia : EntityData
    {
        public static Trivia FromJson(string json) => JsonConvert.DeserializeObject<Trivia>(json, TriviaAPI.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Trivia self) => JsonConvert.SerializeObject(self, TriviaAPI.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}