// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using DemographicsAPI;
//
//    var demographics = Demographics.FromJson(jsonString);

namespace DemographicsAPI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Demographics
    {
        [JsonProperty("Male")]
        public string Male { get; set; }

        [JsonProperty("Female")]
        public string Female { get; set; }

        [JsonProperty("NineteenAndUnder")]
        public string NineteenAndUnder { get; set; }

        [JsonProperty("TwentytoThirtyNine")]
        public string TwentytoThirtyNine { get; set; }

        [JsonProperty("FourtyToFiftyNine")]
        public string FourtyToFiftyNine { get; set; }

        [JsonProperty("SixtyToSeventyNine")]
        public string SixtyToSeventyNine { get; set; }

        [JsonProperty("EightyAndOver")]
        public string EightyAndOver { get; set; }
    }

    public partial class Demographics
    {
        public static Demographics FromJson(string json) => JsonConvert.DeserializeObject<Demographics>(json, DemographicsAPI.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Demographics self) => JsonConvert.SerializeObject(self, DemographicsAPI.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}