// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using RobloxUserGet;
//
//    var robloxUser = RobloxUser.FromJson(jsonString);

namespace RobloxUserGet
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class RobloxUser
    {
        [JsonProperty("data")]
        public Datum[] Data { get; set; }
    }

    public partial class Datum
    {
        [JsonProperty("requestedUsername")]
        public string RequestedUsername { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("displayName")]
        public string DisplayName { get; set; }
    }

    public partial class RobloxUser
    {
        public static RobloxUser FromJson(string json) => JsonConvert.DeserializeObject<RobloxUser>(json, RobloxUserGet.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this RobloxUser self) => JsonConvert.SerializeObject(self, RobloxUserGet.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}