// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AvatarAPI;
//
//    var avatar = Avatar.FromJson(jsonString);

namespace AvatarAPI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Avatar
    {
        [JsonProperty("assetIds")]
        public long[] AssetIds { get; set; }
    }

    public partial class Avatar
    {
        public static Avatar FromJson(string json) => JsonConvert.DeserializeObject<Avatar>(json, AvatarAPI.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Avatar self) => JsonConvert.SerializeObject(self, AvatarAPI.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}